name: Deploying Lambda
on:
  push:
    branches:
      - main
jobs:
  lambda1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout      
        uses: actions/checkout@v3
      - name: Set up Go        
        uses: actions/setup-node@v3
        with:
          node-version: 16  
      - name: Build Golang code
        run: go build -o main ./aws-lambda-gitactions       